### ISSUE TITLE
Cannot use sample_qubo_quantum_task of BraketSampler

### ISSUE THREAD

**Issue by AoyuQC** [aws/amazon-braket-ocean-plugin-python#63] opened 2021-11-29 07:38 UTC
**Describe the bug**
Cannot use the example from [tutorial](https://amazon-braket-ocean-plugin-python.readthedocs.io/en/latest/_apidoc/braket.ocean_plugin.braket_sampler.html) to test the sample_qubo_quantum_task function of BraketSampler. It will have error message:  **BinaryQuadraticModelStructureError: Problem graph incompatible with solver**

**To reproduce**
`from braket.ocean_plugin import BraketSampler`
`sampler = BraketSampler(s3_folder, "arn:aws:braket:::device/qpu/d-wave/Advantage_system4")`
`Q = {(0, 0): -1, (4, 4): -1, (0, 4): 2}`
`task = sampler.sample_qubo_quantum_task(Q, resultFormat="HISTOGRAM", shots=100)`
`sampleset = BraketSampler.get_task_sample_set(task)`

**Expected behavior**
run without errors

**Screenshots or logs**

![Screen Shot 2021-11-29 at 3 33 40 PM](https://user-images.githubusercontent.com/4879237/143826648-9a852cc1-10ae-4f00-a7af-d66ea46c4ba3.png)

**System information**
A description of your system. Please provide:
- **Amazon Braket Python Ocean Plugin version**:1 .0.6
- **Amazon Braket Python SDK version**:1.9.5.post0
- **Amazon Braket Python Schemas version**: 1.4.1
- **Python version**:3.7.12

**Additional context**

**Comment by math411** [comment] 2021-12-10 19:00
In https://github.com/aws/amazon-braket-ocean-plugin-python/pull/64, more verbose logging was added. This particular issue was caused by the topology of the D-Wave specified in the code being used. The qubit set starts at an index of 30 in this case.

**Comment by math411** [comment] 2022-01-03 23:45
Closing this issue out.

**Closed by math411** 2022-01-03 23:45 UTC
Labels: bug
